SSH port for plugin call to log collector
Fixes the following error:
    ERROR: execute_python_eval: __init__()
    missing 1 required positional argument: 'port_ssh'

Changes:
    - Added port variable argument

Tested:
    - Ran chnages from sandbox.

Change-Id: I0e75b757022e3cbfdc06480fdc88af7024fa4dd8
Signed-off-by: George Keishing <gkeishin@in.ibm.com>