Fix import circularity
state.py imports both utils.robot (and lib/state_manager.robot which
imports utils.robot).  utils.robot imports lib/boot_utils.robot which
ultimately tries to import state.py.  This creates a circular import
stack which causes failures:

[ WARN ] Imported library '/afs/rchland.ibm.com/usr6/micwalsh/git/
  openbmc-test-automation/lib/state.py' contains no keywords.
[ ERROR ] Error in file '/afs/rchland.ibm.com/usr6/micwalsh/git/
  openbmc-test-automation/extended/obmc_boot_test_resource.robot':
  Importing test library '/afs/rchland.ibm.com/usr6/micwalsh/git/
  openbmc-test-automation/lib/obmc_boot_test.py' failed:
  AttributeError: 'module' object has no attribute 'return_state_constant'

state.py no longer has need of utils.robot or state_manager.robot so
references to them are being deleted.

Change-Id: I0ae40e7d88b90033cc93b36cdd58207f1b33c681
Signed-off-by: Michael Walsh <micwalsh@us.ibm.com>