Fix eSEL FFDC index error
This is because of an eSEL bug openbmc/openbmc#1297.

From the robot framework documentation "The execution is not continued
if the failure is caused by invalid syntax, timeout, or fatal exception."

"Resolving variable '${esel_data[0]}' failed:
IndexError: list index out of range" which is a fatal exception.

Resolves openbmc/openbmc-test-automation#451

Change-Id: I64c4d039e60eadfc6d5e436482bf0d9c377f7b54
Signed-off-by: George Keishing <gkeishin@in.ibm.com>