Handle Redfish login for Legacy REST supported systems
Changes:
    - Add ignore directive for boot test login try

Note:
   - We will sunset legacy REST by Q4 2023 year end.

Fixes the following error::
REST Host Code Update :: Do a PNOR code update by uploading image ... | FAIL |
ValueError: bmc_redfish.__init__() was never successfully run.
It is likely that the target BMC firmware code level does not support redfish.

Tested:
    - Test from sandbox

Change-Id: Iec6281e06cd76150512bbfa724cba30f156b6a49
Signed-off-by: George Keishing <gkeishin@in.ibm.com>