Fix logging error in robot resource file
Reason:
    ValueError: Argument 'stream' got value 'WARN' that
    cannot be converted to 'stdout' or 'stderr'.

Changes:
    - Fixed the Log To Console messaging

Tested:
   - NA

Change-Id: I651bd276308597d7541431436a3395686bd82490
Signed-off-by: George Keishing <gkeishin@in.ibm.com>